import type { MarketingProduct, MarketingProductSlug } from '@/contracts/marketing-product.draft'

export type ProductSlug = MarketingProductSlug

export const PRODUCTS: Readonly<Record<ProductSlug, MarketingProduct>> = {
  'resume-builder': {
    slug: 'resume-builder',
    label: 'AI Resume Builder',
    headline: 'A resume that makes the fit obvious.',
    summary: 'Turn the experience you already have into a focused resume built around the role you want next.',
    overview: [
      'Jobwhisper reads the role alongside your real experience, then helps you shape a resume around what that employer needs to see.',
      'Nothing is sent automatically. You review the language, keep what sounds like you, and export only when the document is ready.',
    ],
    workflow: [
      { title: 'Set the target', body: 'Paste the job description or describe the role you want.' },
      { title: 'Bring your experience', body: 'Upload an existing resume or build your history from scratch.' },
      { title: 'Tailor the story', body: 'Review focused suggestions for your summary, skills, and experience.' },
      { title: 'Finish and export', body: 'Choose a layout, make final edits, and download the result.' },
    ],
    outcome: 'A credible, role-specific resume that helps a recruiter understand your fit faster.',
    faqs: [
      { question: 'Will Jobwhisper invent experience?', answer: 'No. Suggestions stay grounded in the experience and context you provide.' },
      { question: 'Can I edit every suggestion?', answer: 'Yes. You can accept, reject, rewrite, or ignore every change before export.' },
      { question: 'Can I create more than one version?', answer: 'Yes. Create a separate tailored version for each role you want to pursue.' },
    ],
    ctaLabel: 'Build my resume',
    ctaHref: '/v3/resume',
    sections: [
      {
        id: 'resume-target',
        eyebrow: 'Start with the destination',
        title: 'Tell us which job you want.',
        body: 'Add the role or paste the job description. Jobwhisper identifies the experience, language, and priorities the employer is looking for before it changes a word.',
        steps: ['Paste a job description', 'Confirm the target role'],
        imageSrc: '/figma-landing/journey-resume.png',
        imageAlt: 'Jobwhisper resume builder tailored to a target role',
      },
      {
        id: 'resume-context',
        eyebrow: 'Keep what is true',
        title: 'Bring your real experience forward.',
        body: 'Upload an existing resume or build from scratch. Your background stays accurate while the most relevant accomplishments become easier to see.',
        steps: ['Import your current resume', 'Keep your voice and facts'],
        imageSrc: '/v3-assets/figma/form-screen-preview.png',
        imageAlt: 'Resume information ready for review',
      },
      {
        id: 'resume-tailor',
        eyebrow: 'Make every line earn its place',
        title: 'Tailor the story, not just the keywords.',
        body: 'Get precise suggestions for the summary, experience, and skills that matter for this application. Accept only the changes that sound like you.',
        steps: ['Review targeted suggestions', 'Accept changes one by one'],
        imageSrc: '/figma-landing/journey-copilot.png',
        imageAlt: 'AI suggestions for improving a resume',
      },
      {
        id: 'resume-finish',
        eyebrow: 'Ready to apply',
        title: 'Leave with a resume built for this opportunity.',
        body: 'Choose a clean template, make the final edits, and export a polished resume you can send with confidence.',
        steps: ['Choose a professional layout', 'Export and start applying'],
        imageSrc: '/figma-landing/journey-jobs.png',
        imageAlt: 'Finished resume ready for a job application',
      },
    ],
  },
  'interview-copilot': {
    slug: 'interview-copilot',
    label: 'Interview Copilot',
    headline: 'Know what to say when the question lands.',
    summary: 'Get relevant, real-time answer support grounded in your resume, the role, and the conversation happening now.',
    overview: [
      'Interview Copilot listens during a live conversation and turns each question into useful talking points grounded in your own background.',
      'The support stays beside the call, so you can focus on the interviewer instead of searching notes or memorizing scripts.',
    ],
    workflow: [
      { title: 'Add your context', body: 'Upload your resume and the job description before the interview.' },
      { title: 'Choose your response style', body: 'Set the tone, length, and level of detail you can use naturally.' },
      { title: 'Start the session', body: 'Share the conversation and keep Copilot visible beside your call.' },
      { title: 'Use the talking points', body: 'Read the response, then answer in your own words.' },
      { title: 'Review afterward', body: 'Return to difficult moments and improve for the next conversation.' },
    ],
    outcome: 'More relevant answers, fewer blank moments, and the confidence to stay present in the interview.',
    faqs: [
      { question: 'Does Copilot answer for me?', answer: 'No. It gives you relevant talking points that you express in your own words.' },
      { question: 'What information does it use?', answer: 'Your resume, the job description, your preferences, and the live conversation.' },
      { question: 'Can the interviewer see it?', answer: 'Copilot is designed to stay in your own workspace while you remain on the call.' },
    ],
    ctaLabel: 'Set up my Copilot',
    ctaHref: '/v3/interview-copilot',
    sections: [
      {
        id: 'copilot-context',
        eyebrow: 'Prepare the context',
        title: 'Give Copilot the same brief you have.',
        body: 'Add your resume and the job description once. Copilot uses both to shape answers around your actual experience instead of giving generic interview advice.',
        steps: ['Upload your resume', 'Add the job description'],
        imageSrc: '/figma-landing/journey-copilot.png',
        imageAlt: 'Copilot using resume and job context',
      },
      {
        id: 'copilot-preferences',
        eyebrow: 'Make it sound like you',
        title: 'Choose the kind of help you want.',
        body: 'Set answer length, tone, and response style before the interview so suggestions are useful at a glance and natural to say out loud.',
        steps: ['Choose concise or detailed answers', 'Set your preferred tone'],
        imageSrc: '/figma-landing/copilot-practice.png',
        imageAlt: 'Copilot response preferences',
      },
      {
        id: 'copilot-live',
        eyebrow: 'During the interview',
        title: 'Stay present while Copilot listens.',
        body: 'As each question is asked, Copilot surfaces a tailored response you can absorb quickly and express in your own words—without leaving the call.',
        steps: ['Hear questions in real time', 'Receive relevant talking points'],
        imageSrc: '/figma-landing/copilot-interviews.png',
        imageAlt: 'Interview Copilot responding during a live interview',
      },
      {
        id: 'copilot-review',
        eyebrow: 'After the conversation',
        title: 'Keep the lessons from every interview.',
        body: 'Review the session, revisit difficult moments, and carry stronger answers into the next conversation.',
        steps: ['Review the conversation', 'Improve the next response'],
        imageSrc: '/v3-assets/copilot-live-preview.png',
        imageAlt: 'Completed Copilot session ready for review',
      },
    ],
  },
  'interview-prep': {
    slug: 'interview-prep',
    label: 'Interview Prep',
    headline: 'Practice until the real interview feels familiar.',
    summary: 'Rehearse realistic questions for the role, get specific feedback, and walk into the conversation knowing what to improve.',
    overview: [
      'Interview Prep recreates the kind of conversation you are preparing for instead of giving you a static list of generic questions.',
      'You answer out loud, handle follow-ups, and receive specific coaching you can use in the next practice round.',
    ],
    workflow: [
      { title: 'Describe the interview', body: 'Add the role, company, interview type, and difficulty.' },
      { title: 'Choose an interviewer', body: 'Select a voice and conversation style that feels natural.' },
      { title: 'Practice out loud', body: 'Answer realistic questions and adaptive follow-ups.' },
      { title: 'Review your feedback', body: 'See where the answer was clear and where it lost impact.' },
      { title: 'Repeat the weak spots', body: 'Retry difficult questions until the response feels natural.' },
    ],
    outcome: 'A calmer, clearer interview performance built through realistic repetition and specific feedback.',
    faqs: [
      { question: 'Are the questions tailored to my role?', answer: 'Yes. The session uses the role, company, difficulty, and context you provide.' },
      { question: 'Do I have to use my microphone?', answer: 'Voice practice gives the most realistic session, because it helps you rehearse the answer out loud.' },
      { question: 'What does the report cover?', answer: 'It highlights answer quality, clarity, structure, delivery, and opportunities to improve.' },
    ],
    ctaLabel: 'Start practicing',
    ctaHref: '/v3/interview-prep',
    sections: [
      {
        id: 'prep-role',
        eyebrow: 'Set the scenario',
        title: 'Practice for the interview you actually have.',
        body: 'Choose the role, company, interview type, and difficulty. Every question is shaped around the opportunity instead of a generic question bank.',
        steps: ['Add role and company context', 'Choose interview difficulty'],
        imageSrc: '/v3-assets/figma/form-screen-preview.png',
        imageAlt: 'Interview practice configuration',
      },
      {
        id: 'prep-interviewer',
        eyebrow: 'Meet your interviewer',
        title: 'Choose a voice and begin naturally.',
        body: 'Pick an interviewer and start a realistic spoken session. The pacing gives you room to think while still feeling like a real conversation.',
        steps: ['Choose an interviewer voice', 'Practice out loud'],
        imageSrc: '/figma-landing/journey-simulator.png',
        imageAlt: 'Candidate meeting an AI practice interviewer',
      },
      {
        id: 'prep-session',
        eyebrow: 'Build the skill',
        title: 'Answer realistic follow-up questions.',
        body: 'The interviewer adapts to what you say, asks follow-ups, and helps you practice the pressure of explaining your experience clearly.',
        steps: ['Respond to role-specific questions', 'Practice follow-up answers'],
        imageSrc: '/figma-landing/copilot-practice.png',
        imageAlt: 'Live AI interview practice session',
      },
      {
        id: 'prep-feedback',
        eyebrow: 'Know what to improve',
        title: 'Turn one practice session into a better next one.',
        body: 'See where your answer was strong, where it wandered, and what would make it more convincing. Then repeat the parts that need work.',
        steps: ['Review specific coaching', 'Retry difficult questions'],
        imageSrc: '/v3-assets/interview-report-maya.png',
        imageAlt: 'Interview practice feedback report',
      },
    ],
  },
  'auto-apply': {
    slug: 'auto-apply',
    label: 'Auto Apply',
    headline: 'Spend your time on the right applications.',
    summary: 'Find roles that fit, review them in one place, and move the applications you choose forward without rebuilding the process every time.',
    overview: [
      'Auto Apply turns your preferences into a focused job-search workflow, from finding relevant openings to tracking what was submitted.',
      'You choose how much control to keep. Review matches yourself or let Jobwhisper move approved applications forward for you.',
    ],
    workflow: [
      { title: 'Set your preferences', body: 'Define the roles, salary, location, seniority, and work style you want.' },
      { title: 'Review your matches', body: 'See the strongest opportunities and why they fit your profile.' },
      { title: 'Prepare the application', body: 'Tailor your resume and confirm the information that will be submitted.' },
      { title: 'Choose your control level', body: 'Apply yourself or allow approved applications to move forward automatically.' },
      { title: 'Track every result', body: 'Follow found, tailored, submitted, and completed applications in one place.' },
    ],
    outcome: 'A focused pipeline of relevant applications without repeating the same search and setup work every day.',
    faqs: [
      { question: 'Does Auto Apply send every application automatically?', answer: 'No. You choose the application method and how much review you want before submission.' },
      { question: 'How are jobs matched?', answer: 'Matches use your target roles, experience, salary, location, seniority, and work preferences.' },
      { question: 'Can I see what was submitted?', answer: 'Yes. The application timeline shows the role, materials, status, and recorded activity.' },
    ],
    ctaLabel: 'Find matching roles',
    ctaHref: '/v3/auto-apply',
    sections: [
      {
        id: 'apply-preferences',
        eyebrow: 'Define the search',
        title: 'Tell us what a good opportunity looks like.',
        body: 'Set the roles, seniority, salary, location, and work style you want. The search stays focused on the jobs worth your attention.',
        steps: ['Choose target roles', 'Set location and salary preferences'],
        imageSrc: '/v3-assets/figma/form-screen-preview.png',
        imageAlt: 'Auto Apply job preference setup',
      },
      {
        id: 'apply-match',
        eyebrow: 'See the fit first',
        title: 'Review matched roles before you apply.',
        body: 'Compare opportunities at a glance, understand why each role fits, and dismiss the ones that do not match your goals.',
        steps: ['Compare match strength', 'Keep or dismiss each role'],
        imageSrc: '/figma-landing/journey-jobs.png',
        imageAlt: 'Matched job opportunities in Jobwhisper',
      },
      {
        id: 'apply-tailor',
        eyebrow: 'Apply with context',
        title: 'Tailor the application to the role.',
        body: 'Use a resume shaped around the job and keep control over what is sent. Your application stays relevant without becoming anonymous automation.',
        steps: ['Tailor the resume', 'Review before submission'],
        imageSrc: '/figma-landing/journey-resume.png',
        imageAlt: 'Resume tailored for an Auto Apply opportunity',
      },
      {
        id: 'apply-track',
        eyebrow: 'Know what happened',
        title: 'Keep every application in one clear pipeline.',
        body: 'See which roles were found, reviewed, tailored, and submitted so you always know where each opportunity stands.',
        steps: ['Track every application', 'Return to the strongest opportunities'],
        imageSrc: '/figma-landing/service-self.png',
        imageAlt: 'Auto Apply application progress',
      },
    ],
  },
}
