import type { MarketingProduct, MarketingProductSlug } from '@/contracts/marketing-product.draft'

export type ProductSlug = MarketingProductSlug

export const PRODUCT_WALKTHROUGHS: Readonly<Record<ProductSlug, readonly string[]>> = {
  'resume-builder': [9, 8, 6, 4, 7, 5].map((index) => `/figma-product-pages/resume-builder-${index}.jpg`),
  'interview-copilot': [4, 1, 5, 8, 7, 13, 6, 9].map((index) => `/figma-product-pages/interview-copilot-${index}.jpg`),
  'interview-prep': [3, 6, 2, 5].map((index) => `/figma-product-pages/interview-prep-${index}.jpg`),
  'auto-apply': [8, 9, 7, 15, 10, 14, 11, 1].map((index) => `/figma-product-pages/auto-apply-${index}.jpg`),
}

export const PRODUCTS: Readonly<Record<ProductSlug, MarketingProduct>> = {
  'resume-builder': {
    slug: 'resume-builder',
    label: 'AI Resume Builder',
    headline: 'A resume that makes the fit obvious.',
    summary: 'Turn the experience you already have into a focused resume built around the role you want next.',
    narrative: `Start with the job you actually want, because a useful resume is not a general record of everything you have ever done. It is a clear explanation of why your experience makes sense for one opportunity. Copy the job description from the role and bring it into Jobwhisper. You can paste the full description, name the company, and confirm the position you are targeting. Jobwhisper reads the responsibilities, required skills, seniority, and language the employer uses before suggesting a change. That gives the work a destination. Next, bring in the experience you already have. Upload your current resume if you have one, choose an existing Jobwhisper resume, or build your history from scratch. The product parses the document and organizes your professional summary, roles, achievements, skills, education, and other relevant details so you do not have to re-enter the same information every time you find a new job. Review the imported information before you continue. Correct dates, titles, company names, and anything that was formatted unusually in the original file. Jobwhisper is meant to help you present your real experience more clearly, not invent experience you do not have. Once your background and the target role are in place, open the resume canvas. The canvas keeps the document visible while the conversation beside it gives you a practical way to direct the work. You can ask Jobwhisper to tailor the resume to the job description, shorten the professional summary, place more emphasis on a particular part of your experience, clarify an achievement, or keep a title exactly as it is. Instead of rewriting the entire document in one hidden step, Jobwhisper proposes changes you can inspect. Read each suggestion in context. Accept the changes that are accurate and sound like you, reject the ones that do not, and continue the conversation when the wording needs another pass. The strongest version will usually make the connection between your work and the role easier to understand. A vague line such as being responsible for onboarding becomes more useful when it explains what you changed, who it helped, and what improved. A long list of unrelated skills becomes more focused when the skills most relevant to the job are easier to find. Your summary should quickly tell a recruiter what kind of work you do, where you have produced results, and why this role is a logical next step. Your experience should show ownership and outcomes without becoming exaggerated. Your skills should support the story already established by the rest of the resume. Keep working through the document until the important evidence is visible without forcing the reader to hunt for it. Then preview the resume as a complete page. Check the hierarchy, spacing, line breaks, and length. Make sure the most important information is not pushed too far down, that every section earns its place, and that the document still sounds like a person rather than a collection of copied keywords. Use the ATS review to understand whether the resume covers the role's important language and whether obvious gaps remain. Treat the score as guidance, not as permission to stuff the page with repeated phrases. If the review points to a missing skill you genuinely have, add evidence for it. If it points to experience you do not have, leave it out. Choose the layout that presents your history cleanly, make any final edits, and export the finished version in the format you need. Save this tailored resume as its own version so your base career information remains reusable. When another serious opportunity appears, begin again with that job description instead of sending the same document everywhere. The process becomes faster because your experience is already organized. You are no longer starting from a blank page, guessing which details matter, or losing an hour to formatting before every application. You are moving from a real job target, to accurate context, to reviewed suggestions, to a finished resume that helps the recruiter understand your fit faster.`,
    overview: [
      'Jobwhisper reads the role alongside your real experience, then helps you shape a resume around what that employer needs to see.',
      'Nothing is sent automatically. You review the language, keep what sounds like you, and export only when the document is ready.',
    ],
    workflow: [
      { title: 'Set the target', body: 'Paste the job description or describe the role you want.' },
      { title: 'Bring your experience', body: 'Upload an existing resume or build your history from scratch.' },
      { title: 'Tailor the story', body: 'Review focused suggestions for your summary, skills, and experience.' },
      { title: 'Finish and export', body: 'Choose a layout, make final edits, and download the result.' },
    ],
    outcome: 'A credible, role-specific resume that helps a recruiter understand your fit faster.',
    faqs: [
      { question: 'Will Jobwhisper invent experience?', answer: 'No. Suggestions stay grounded in the experience and context you provide.' },
      { question: 'Can I edit every suggestion?', answer: 'Yes. You can accept, reject, rewrite, or ignore every change before export.' },
      { question: 'Can I create more than one version?', answer: 'Yes. Create a separate tailored version for each role you want to pursue.' },
      { question: 'Can I start with my current resume?', answer: 'Yes. Upload your existing resume and Jobwhisper will preserve the facts while helping you tailor the presentation.' },
      { question: 'Does it check for ATS fit?', answer: 'Yes. The review highlights important language and gaps so you can improve fit without stuffing keywords.' },
      { question: 'Which formats can I export?', answer: 'You can finish the document in Jobwhisper and download a polished version ready for your application.' },
    ],
    ctaLabel: 'Build my resume',
    ctaHref: '/v3/resume',
    sections: [
      {
        id: 'resume-builder-1',
        eyebrow: 'Start with the job',
        title: 'Paste the job description.',
        body: 'Upload your resume, name the role and company, then paste the posting. Jobwhisper reads it before changing a word.',
        steps: [],
        imageSrc: '/figma-product-pages/resume-builder-9.jpg',
        imageAlt: 'Configure your resume, with the job description pasted in',
      },
      {
        id: 'resume-builder-2',
        eyebrow: 'Direct the rewrite',
        title: 'Ask for changes in plain words.',
        body: 'The resume stays on screen while you chat. Ask for a headline, more emphasis or a shorter summary, and read the reply.',
        steps: [],
        imageSrc: '/figma-product-pages/resume-builder-8.jpg',
        imageAlt: 'Chat beside the resume canvas proposing a professional headline',
      },
      {
        id: 'resume-builder-3',
        eyebrow: 'You decide',
        title: 'Accept or reject every edit.',
        body: 'Each proposed line is marked on the page with a tick and a cross. Take the ones that are true and refuse the rest.',
        steps: [],
        imageSrc: '/figma-product-pages/resume-builder-6.jpg',
        imageAlt: 'Proposed edits marked inline on the resume with accept and reject controls',
      },
      {
        id: 'resume-builder-4',
        eyebrow: 'Check the fit',
        title: 'See your ATS score.',
        body: 'Scored against the posting: structure, impact, brevity, keyword match, what is working, and the terms you never say.',
        steps: [],
        imageSrc: '/figma-product-pages/resume-builder-4.jpg',
        imageAlt: 'ATS score panel showing a 96 percent match and a keyword breakdown',
      },
      {
        id: 'resume-builder-5',
        eyebrow: 'Edit it yourself',
        title: 'Change any field by hand.',
        body: 'Open the editor for titles, companies, dates and bullets. Reorder the sections or add new ones whenever you prefer.',
        steps: [],
        imageSrc: '/figma-product-pages/resume-builder-7.jpg',
        imageAlt: 'Manual resume editor with fields for job title, company, dates and bullets',
      },
      {
        id: 'resume-builder-6',
        eyebrow: 'Finish and send',
        title: 'See the page break, then download.',
        body: 'A marker shows where the second page starts, so nothing splits awkwardly. Export once the layout reads the way you want.',
        steps: [],
        imageSrc: '/figma-product-pages/resume-builder-5.jpg',
        imageAlt: 'Resume preview showing the page break marker above skills and education',
      },
    ],
  },
  'interview-copilot': {
    slug: 'interview-copilot',
    label: 'Interview Copilot',
    headline: 'Know what to say when the question lands.',
    summary: 'Get relevant, real-time answer support grounded in your resume, the role, and the conversation happening now.',
    narrative: `Interview Copilot works best when it understands the same opportunity you are preparing to discuss. Begin before the call by adding the resume you applied with and the job description for the role. This gives Jobwhisper the facts of your background, the employer's priorities, and the language surrounding the position. Review the extracted context and make sure the role, company, and experience are correct. If there are projects, achievements, or responsibilities you especially want the Copilot to remember, include them in the knowledge you provide. You can also add notes about the company, the interview stage, or topics you expect to cover. The goal is not to produce a script you must memorize. It is to give the Copilot enough reliable context to surface useful talking points when the conversation moves quickly. Next, choose how you want the help to appear. Set the answer length, tone, and level of detail so the responses match the way you naturally communicate. A concise setting is useful when you need a few points you can absorb at a glance. A more detailed setting can help during a technical, strategic, or case-based conversation where structure matters. Choose the model and language that fit the interview, and confirm the audio source the session should listen to. Before the real meeting, test the microphone and system audio. Make sure the interviewer can be heard by the Copilot and that the response panel remains visible without covering the call controls or your notes. When the interview begins, start the Copilot session and keep your attention on the person speaking. Jobwhisper listens for the question, considers the live conversation alongside your resume and the job description, and generates a response grounded in that context. Read the suggestion as support, not as a line you must recite word for word. The most natural use is to take the structure, select the points that are true for you, and answer in your own voice. If the interviewer asks about a difficult stakeholder, the response can remind you of a relevant example and organize it around the situation, your action, and the result. If the interviewer asks a product question, the response can help you connect your decision to the customer, evidence, tradeoffs, and outcome. If the question is unclear, Copilot can help identify what the interviewer may be trying to learn so you can ask a useful clarifying question instead of rushing into an answer. The controls stay close throughout the session. Pause listening when the meeting moves into private discussion or when you do not need support. Resume when the interview continues. Ask a direct question in the Copilot panel when you need help with a specific moment. Adjust the response length if suggestions are too dense to use during a live call. The tool is designed to reduce blank moments and searching, but you remain responsible for what you say. Never claim an accomplishment, skill, or decision that is not yours. Use the prompt as a reminder of your real evidence and keep the conversation human. As the interview develops, the earlier context matters. Follow-up questions often depend on what was said several minutes ago, so the Copilot considers the conversation rather than treating every sentence as an isolated prompt. That makes it useful for interviews, hiring-manager discussions, technical screens, and other high-pressure conversations where the right answer depends on both the question and what has already been established. When the call ends, stop the session and review the conversation. Return to the moments where you hesitated, where the interviewer pushed deeper, or where your answer did not land as clearly as you wanted. Compare the question, the available talking points, and the answer you gave. Capture a stronger version while the conversation is still fresh. Over time, the review becomes more than a transcript. It becomes a record of the questions you are encountering, the stories that work, and the areas that still need practice. The web experience is useful when you can keep a browser workspace beside the call. The desktop experience gives you a smaller, focused window that can stay within reach while you work in your meeting app. In either version, the journey is the same: prepare reliable context, choose the kind of help you can use naturally, test the session, stay present during the interview, and learn from the conversation afterward. The outcome is not a robotic interview. It is a better-supported version of you, able to find the relevant experience faster, organize an answer under pressure, and remain engaged with the person on the other side of the call.`,
    overview: [
      'Interview Copilot listens during a live conversation and turns each question into useful talking points grounded in your own background.',
      'The support stays beside the call, so you can focus on the interviewer instead of searching notes or memorizing scripts.',
    ],
    workflow: [
      { title: 'Add your context', body: 'Upload your resume and the job description before the interview.' },
      { title: 'Choose your response style', body: 'Set the tone, length, and level of detail you can use naturally.' },
      { title: 'Start the session', body: 'Share the conversation and keep Copilot visible beside your call.' },
      { title: 'Use the talking points', body: 'Read the response, then answer in your own words.' },
      { title: 'Review afterward', body: 'Return to difficult moments and improve for the next conversation.' },
    ],
    outcome: 'More relevant answers, fewer blank moments, and the confidence to stay present in the interview.',
    faqs: [
      { question: 'Does Copilot answer for me?', answer: 'No. It gives you relevant talking points that you express in your own words.' },
      { question: 'What information does it use?', answer: 'Your resume, the job description, your preferences, and the live conversation.' },
      { question: 'Can the interviewer see it?', answer: 'Copilot is designed to stay in your own workspace while you remain on the call.' },
      { question: 'Can I change the answer length?', answer: 'Yes. Choose concise or detailed support before the call and adjust it when the conversation changes.' },
      { question: 'Does it work with meeting apps?', answer: 'Copilot runs beside your meeting workspace so you can stay in the conversation while receiving support.' },
      { question: 'Can I review the session later?', answer: 'Yes. Revisit difficult questions and capture stronger responses while the conversation is still fresh.' },
    ],
    ctaLabel: 'Set up my Copilot',
    ctaHref: '/v3/interview-copilot',
    sections: [
      {
        id: 'interview-copilot-1',
        eyebrow: 'Give it the context',
        title: 'Add the role and your resume.',
        body: 'Target role, company and resume, plus any documents. Say what you want Copilot to lean on and it works from that.',
        steps: [],
        imageSrc: '/figma-product-pages/interview-copilot-4.jpg',
        imageAlt: 'Configure your interview, with target role, company and supporting documents',
      },
      {
        id: 'interview-copilot-2',
        eyebrow: 'Set how it answers',
        title: 'Choose the style and model.',
        body: 'Default, headlines or coaching. Short, medium or long. Then pick the model: OpenAI, Claude, Gemini, Kimi or Qwen.',
        steps: [],
        imageSrc: '/figma-product-pages/interview-copilot-1.jpg',
        imageAlt: 'Response preferences with the model picker open',
      },
      {
        id: 'interview-copilot-3',
        eyebrow: 'Connect the call',
        title: 'Share the tab and its audio.',
        body: 'Choose the tab, window or screen your interview runs in, and leave tab audio on so Copilot can hear the questions.',
        steps: [],
        imageSrc: '/figma-product-pages/interview-copilot-5.jpg',
        imageAlt: 'Browser dialog choosing which tab to share, with tab audio enabled',
      },
      {
        id: 'interview-copilot-4',
        eyebrow: 'Two things to allow',
        title: 'Turn on your microphone.',
        body: 'Screen shared, audio captured, microphone connected. Jobwhisper listens only while the session is live.',
        steps: [],
        imageSrc: '/figma-product-pages/interview-copilot-8.jpg',
        imageAlt: 'Setup checklist showing the screen shared and the microphone being requested',
      },
      {
        id: 'interview-copilot-5',
        eyebrow: 'During the interview',
        title: 'Answers as the questions land.',
        body: 'Every question appears with an answer drawn from your own history. Ask the assistant for a different angle mid-call.',
        steps: [],
        imageSrc: '/figma-product-pages/interview-copilot-7.jpg',
        imageAlt: 'Live response pane with suggested answers and an AI assistant panel',
      },
      {
        id: 'interview-copilot-6',
        eyebrow: 'After you finish',
        title: 'The report writes itself.',
        body: 'Transcript assembled, answers reviewed, scored against the rubric, and recommendations written.',
        steps: [],
        imageSrc: '/figma-product-pages/interview-copilot-13.jpg',
        imageAlt: 'Interview report being prepared, step by step',
      },
      {
        id: 'interview-copilot-7',
        eyebrow: 'What happened',
        title: 'Score, talk time and feedback.',
        body: 'How long you spoke for against the interviewer, what went well, and what needs work with your wording quoted back.',
        steps: [],
        imageSrc: '/figma-product-pages/interview-copilot-6.jpg',
        imageAlt: 'Report summary with a score, a talk-time split and written feedback',
      },
      {
        id: 'interview-copilot-8',
        eyebrow: 'What to fix next',
        title: 'Knowledge gaps, then better questions.',
        body: 'Where the evidence was missing, and the questions worth rehearsing before the next conversation.',
        steps: [],
        imageSrc: '/figma-product-pages/interview-copilot-9.jpg',
        imageAlt: 'Report section listing knowledge gaps and suggested questions for future sessions',
      },
    ],
  },
  'interview-prep': {
    slug: 'interview-prep',
    label: 'Interview Prep',
    headline: 'Practice until the real interview feels familiar.',
    summary: 'Rehearse realistic questions for the role, get specific feedback, and walk into the conversation knowing what to improve.',
    narrative: `Interview Prep turns preparation into a realistic practice cycle instead of a list of questions you read silently. Start with the interview you actually have. Choose the resume connected to the opportunity, add the job description, name the company and role, and select the kind of interview you expect. You can prepare for behavioral questions, a hiring-manager conversation, a technical screen, a case discussion, or a broader practice session. Set the difficulty and the amount of time you want to spend so the session matches the pressure and depth of the real conversation. Jobwhisper uses this context to decide what the interviewer should ask and what a strong answer needs to demonstrate. Choose an interviewer voice and conversation style that feels comfortable enough to begin but realistic enough to challenge you. Check your microphone, find a quiet place, and answer out loud. Speaking changes the exercise. An answer that looked clear in your head may become too long, lose its structure, or hide the result when you try to say it. The simulated interviewer gives you the space to discover that before the real interview. The first question is shaped around the role and the stage you selected. Listen fully, take a moment, and answer as you would in the real meeting. The interviewer can ask follow-up questions based on what you say, so a vague claim may be tested and a promising example may be explored in more detail. When you describe a project, explain the context, the decision you owned, the action you took, and the result. When the question concerns conflict or failure, make your responsibility clear and show what changed because of the experience. When the question is strategic, explain the evidence and tradeoffs behind the decision rather than jumping straight to the conclusion. Continue through the session without trying to make every answer perfect. The first run is diagnostic. It shows where you freeze, repeat yourself, rely on general statements, or forget the evidence that makes a story convincing. When the session ends, open the report and read the feedback alongside the questions. Look at clarity, relevance, structure, specificity, and delivery. Notice where the answer directly addressed the question and where it wandered. Check whether the example was credible, whether your role was distinct from the team's work, and whether the result was measurable or otherwise concrete. Review delivery patterns too. A strong example can lose impact when the opening is too long or the conclusion never arrives. Choose the questions that need another attempt and practice them again. Do not memorize an entire paragraph. Build a reliable structure and remember the evidence you want to include. Try a shorter opening. Move the most important result earlier. Replace a broad statement with one decision you actually made. Explain the tradeoff that made the situation difficult. Repeat until the answer feels natural enough to adapt when the wording of the real question changes. Use the next session to increase difficulty, change the interview style, or focus on a different part of the role. One round might concentrate on leadership stories, another on product judgment, and another on the technical or commercial details the company is likely to test. If you are preparing for several stages, create a practice setup for each one instead of assuming the same answers will work everywhere. The recruiter screen needs a clear career story and motivation. The hiring manager may probe ownership and outcomes. A panel may test how you reason with incomplete information and respond to different perspectives. By practicing each context, you learn how to carry the same truthful experience into different conversations. The purpose is not to remove every pause. It is to make the real interview feel recognizable. You have already heard difficult questions, found the evidence you want to use, and practiced recovering when the first answer was not strong enough. You enter the meeting with fewer unknowns and a clearer sense of what good looks like. From setting the scenario, to answering out loud, to receiving specific feedback, to repeating the weak moments, every part of Interview Prep is designed to turn nervous preparation into visible improvement you can carry into the actual conversation.`,
    overview: [
      'Interview Prep recreates the kind of conversation you are preparing for instead of giving you a static list of generic questions.',
      'You answer out loud, handle follow-ups, and receive specific coaching you can use in the next practice round.',
    ],
    workflow: [
      { title: 'Describe the interview', body: 'Add the role, company, interview type, and difficulty.' },
      { title: 'Choose an interviewer', body: 'Select a voice and conversation style that feels natural.' },
      { title: 'Practice out loud', body: 'Answer realistic questions and adaptive follow-ups.' },
      { title: 'Review your feedback', body: 'See where the answer was clear and where it lost impact.' },
      { title: 'Repeat the weak spots', body: 'Retry difficult questions until the response feels natural.' },
    ],
    outcome: 'A calmer, clearer interview performance built through realistic repetition and specific feedback.',
    faqs: [
      { question: 'Are the questions tailored to my role?', answer: 'Yes. The session uses the role, company, difficulty, and context you provide.' },
      { question: 'Do I have to use my microphone?', answer: 'Voice practice gives the most realistic session, because it helps you rehearse the answer out loud.' },
      { question: 'What does the report cover?', answer: 'It highlights answer quality, clarity, structure, delivery, and opportunities to improve.' },
      { question: 'Can I choose the interview type?', answer: 'Yes. Practice behavioral, hiring-manager, technical, case, or broader interview sessions.' },
      { question: 'Can I retry difficult questions?', answer: 'Yes. Use the feedback to repeat weak moments until the structure feels natural rather than memorized.' },
      { question: 'Can I practice for several interview stages?', answer: 'Yes. Create a different setup for each stage so the questions match what that conversation is likely to test.' },
    ],
    ctaLabel: 'Start practicing',
    ctaHref: '/v3/interview-prep',
    sections: [
      {
        id: 'interview-prep-1',
        eyebrow: 'Pick your interviewer',
        title: 'Choose a voice and begin.',
        body: 'Six interviewers with real backgrounds: founder, engineering manager, PM, designer. Check your microphone, then start.',
        steps: [],
        imageSrc: '/figma-product-pages/interview-prep-3.jpg',
        imageAlt: 'Choose interviewer voice, with six interviewer profiles',
      },
      {
        id: 'interview-prep-2',
        eyebrow: 'Speak your answers',
        title: 'Hold a real conversation.',
        body: 'You talk, the interviewer follows up on what you said, and a live transcript records both sides as the session runs.',
        steps: [],
        imageSrc: '/figma-product-pages/interview-prep-6.jpg',
        imageAlt: 'Live interview simulator with the interviewer, you, and a running transcript',
      },
      {
        id: 'interview-prep-3',
        eyebrow: 'Read the verdict',
        title: 'Get scored out of 100.',
        body: 'A written summary of what the interviewer actually heard, with what went well and what needs work, point by point.',
        steps: [],
        imageSrc: '/figma-product-pages/interview-prep-2.jpg',
        imageAlt: 'Interview report summary with a score out of 100 and written feedback',
      },
      {
        id: 'interview-prep-4',
        eyebrow: 'See the detail',
        title: 'Compare yourself line by line.',
        body: 'A scorecard for every element, and metrics for clarity, structure, evidence, role fit and confidence against the interviewer.',
        steps: [],
        imageSrc: '/figma-product-pages/interview-prep-5.jpg',
        imageAlt: 'Interview report scorecard and metrics comparing you with the interviewer',
      },
    ],
  },
  'auto-apply': {
    slug: 'auto-apply',
    label: 'Auto Apply',
    headline: 'Spend your time on the right applications.',
    summary: 'Find roles that fit, review them in one place, and move the ones you choose forward without rebuilding the process.',
    narrative: `Auto Apply begins by defining what a worthwhile opportunity looks like for you. Add the resume you want the search to use, then review the information Jobwhisper extracts from it. Confirm your current role, experience, skills, education, and contact details so the applications are built from accurate information. Complete the contact fields an employer is likely to request, including your location, phone number, postal information, and work authorization. Some of this may already be available from your resume, but checking it now prevents the same correction from appearing across many applications later. Next, set the job preferences that will guide the search. Choose the roles you want, the level of seniority, preferred employment type, salary range, locations, remote or onsite expectations, and any visa or authorization constraints. Be specific enough to protect your time without making the search so narrow that relevant variations disappear. If you would accept several closely related roles, include them. If a location, salary floor, or work arrangement is non-negotiable, make that explicit. Add the additional information that frequently appears in application forms so Jobwhisper can prepare consistent answers without asking you to rebuild the same profile for every company. Once the setup is complete, the Auto Apply agents take on different parts of the workflow. Scout looks for openings across supported sources. Filter compares those roles with the preferences and experience you provided. The result is a focused set of opportunities rather than an endless job board. Open a match to understand the company, role, location, compensation when available, responsibilities, and the reasons it may fit. Review the source and decide whether the opportunity deserves an application. Dismiss roles that are clearly wrong so the pipeline stays useful. Save or approve the ones you want to pursue. A match is a recommendation, not a promise, so use your judgment when a title hides a different level of responsibility or when the company context changes what the role means. When you choose a job, Tailor prepares the application materials around that opportunity. The resume can be adapted to make the most relevant experience easier to see while keeping your facts intact. Review the proposed version just as you would in the Resume Builder. Confirm that titles, dates, achievements, skills, and contact information remain correct. Make sure the application reflects why you fit the job without copying language you cannot support. Choose how much control you want over submission. You can keep a review step and apply yourself, or allow approved applications to move forward through the automated workflow when the supported source and your settings permit it. Driver handles the repetitive browser work, completes known fields, and records what happened. When an application asks for something new, ambiguous, or sensitive, review it rather than allowing automation to guess. Some employers use custom questions, assessments, external accounts, or pages that require a manual decision. Auto Apply should make those moments visible, not hide them. Follow the activity in Your Jobs. Each opportunity moves through a clear pipeline, from found, to matched, to prepared, to submitted, completed, skipped, or needing attention. Open the application timeline to see what material was used, what information was entered, and where the process stopped. If a source page changes, a required field is missing, or the connection is interrupted, the status should tell you what needs to happen next. Resume the work once the issue is corrected. The record matters because automation is only useful when you can understand and trust what it did. Use the pipeline as a working shortlist, not as a vanity counter. Pay attention to which roles lead to recruiter responses and which searches produce noise. Refine your preferences when the matches are too broad, the level is wrong, or the location does not fit. Improve the resume when strong matches repeatedly fail to progress. Return to promising opportunities, prepare for replies, and keep the rest of your job-search work connected to the same role context. The value of Auto Apply is not sending the largest possible number of applications. It is removing repeated searching, form filling, and tracking so you can spend more time judging opportunities, strengthening important applications, preparing for interviews, and responding when a company shows interest. The complete journey moves from an accurate profile, to clear preferences, to relevant matches, to tailored materials, to controlled submission, to a visible record of every result. You keep the decisions that require judgment while Jobwhisper carries the repetitive work between them.`,
    overview: [
      'Auto Apply turns your preferences into a focused job-search workflow, from finding relevant openings to tracking what was submitted.',
      'You choose how much control to keep. Review matches yourself or let Jobwhisper move approved applications forward for you.',
    ],
    workflow: [
      { title: 'Set your preferences', body: 'Define the roles, salary, location, seniority, and work style you want.' },
      { title: 'Review your matches', body: 'See the strongest opportunities and why they fit your profile.' },
      { title: 'Prepare the application', body: 'Tailor your resume and confirm the information that will be submitted.' },
      { title: 'Choose your control level', body: 'Apply yourself or allow approved applications to move forward automatically.' },
      { title: 'Track every result', body: 'Follow found, tailored, submitted, and completed applications in one place.' },
    ],
    outcome: 'A focused pipeline of relevant applications without repeating the same search and setup work every day.',
    faqs: [
      { question: 'Does Auto Apply send every application automatically?', answer: 'No. You choose the application method and how much review you want before submission.' },
      { question: 'How are jobs matched?', answer: 'Matches use your target roles, experience, salary, location, seniority, and work preferences.' },
      { question: 'Can I see what was submitted?', answer: 'Yes. The application timeline shows the role, materials, status, and recorded activity.' },
      { question: 'Can I review a job before applying?', answer: 'Yes. Open every match, understand why it fits, and approve or dismiss it before moving forward.' },
      { question: 'Will it tailor my resume?', answer: 'Yes. Jobwhisper can prepare a role-specific version while keeping your experience and facts accurate.' },
      { question: 'What happens when an application needs attention?', answer: 'The application pauses with a clear status so you can answer a new, ambiguous, or sensitive question yourself.' },
    ],
    ctaLabel: 'Find matching roles',
    ctaHref: '/v3/auto-apply',
    sections: [
      {
        id: 'auto-apply-1',
        eyebrow: 'Say what you want',
        title: 'Set the roles and the level.',
        body: 'Up to five target roles and one experience level, from entry to executive, so the search knows what counts as a fit.',
        steps: [],
        imageSrc: '/figma-product-pages/auto-apply-8.jpg',
        imageAlt: 'Job preferences with desired roles and an experience level being chosen',
      },
      {
        id: 'auto-apply-2',
        eyebrow: 'Choose your way',
        title: 'Hands-off, or pick your own.',
        body: 'Apply automatically, review a ranked list yourself, or apply from the job boards with the browser extension.',
        steps: [],
        imageSrc: '/figma-product-pages/auto-apply-9.jpg',
        imageAlt: 'Choosing between full auto apply, picking your own jobs, and the browser extension',
      },
      {
        id: 'auto-apply-3',
        eyebrow: 'Set the pace',
        title: 'Cap how many go out daily.',
        body: 'Choose applications per day and the time they start. Jobwhisper submits up to that quota and then stops.',
        steps: [],
        imageSrc: '/figma-product-pages/auto-apply-7.jpg',
        imageAlt: 'Automation settings for applications per day and a daily start time',
      },
      {
        id: 'auto-apply-4',
        eyebrow: 'Watch it work',
        title: 'Scout, filter, tailor, apply.',
        body: 'Four agents in sequence: 60 postings found, 10 over the match bar, 10 tailored, every step logged with its reason.',
        steps: [],
        imageSrc: '/figma-product-pages/auto-apply-15.jpg',
        imageAlt: 'Agent dashboard showing found, matched and tailored counts with a run log',
      },
      {
        id: 'auto-apply-5',
        eyebrow: 'Review the matches',
        title: 'See why each job scored.',
        body: 'Each match breaks its percentage down, names the resume that will be sent, and waits for you to apply or skip.',
        steps: [],
        imageSrc: '/figma-product-pages/auto-apply-10.jpg',
        imageAlt: 'Matched jobs list with a match breakdown and apply controls',
      },
      {
        id: 'auto-apply-6',
        eyebrow: 'On the job boards',
        title: 'It fills the forms for you.',
        body: 'The extension works inside LinkedIn, Indeed, Glassdoor and Workable, completing each page of the application.',
        steps: [],
        imageSrc: '/figma-product-pages/auto-apply-14.jpg',
        imageAlt: 'The extension filling a LinkedIn application beside its board panel',
      },
      {
        id: 'auto-apply-7',
        eyebrow: 'The awkward questions',
        title: 'Screening answers, handled.',
        body: 'Sponsorship, tech stack, how you heard about the role: filled from your profile instead of typed again each time.',
        steps: [],
        imageSrc: '/figma-product-pages/auto-apply-11.jpg',
        imageAlt: 'Additional screening questions being completed on a LinkedIn application',
      },
      {
        id: 'auto-apply-8',
        eyebrow: 'Nothing hidden',
        title: 'Every decision is logged.',
        body: 'A live feed shows what was searched, what was applied to, and the reason anything was skipped.',
        steps: [],
        imageSrc: '/figma-product-pages/auto-apply-1.jpg',
        imageAlt: 'Glassdoor search with the extension panel logging each decision',
      },
    ],
  },
}
